### ISSUE TITLE
Clarification on version numbers

### ISSUE THREAD

**Issue by chindraba-work** [LunarWatcher/auto-pairs#11]
Since you've added the meta templates for GitHub, and are now doing releases, How are you "numbering" them?

If not doing so already, perhaps using [Semantic Versioning](https://semver.org/spec/v2.0.0.html). Especially helpful as you are making breaking changes now.

Adding your choice to the README  could help others who come along and try out the "new and improved" version.

**Comment by LunarWatcher** [comment]
Not gonna lie, I've pretty much planned the version system around a bump to v3, with a "normal" system from there. I also haven't given versioning too much thought, and I don't really have an excuse. There's already a major version bump, so figured that'd justify some of the breaking changes, but that philosophy might be more geared towards other software rather than plugins with an API.

I'm also not a fan of semver. Never been able to properly understand when what should be incremented.

You're still right that sticking to release candidates over real versions might not be the best idea, but there's still a reason they're labeled alpha: at least two versions so far have contained breaking bugs (one of which slipped through because I don't map `<BS>` and committed a dumdum), which feels harder to justify unless they're proper alpha releases. Alpha (and beta) releases also only really make sense if they're towards a single version. 

After 3.0.0, I'm gonna do a bit more sane versioning, but I just don't know what to do in the meanwhile. Can't exactly do pre-1.0.0 versions either :')

**Comment by chindraba-work** [comment]
Alpha (and beta) is expected to have breaking changes, and just about any instability you can imagine. Maybe even one or two nobody ever envisioned.

Semver's system is pretty sane. first part don't need to change until something breaks relative to the interface. (Without an API involved that would be the user's way of using it.) Second part changes when there's a non-breaking change in the interface. (New function, new shortcut, etc.) Everything else changes the third part. Any version with something after the third part is best-guess and really means "I'm working on it, _YMMV_."

The version number with alpha or beta suggests what the version might be when done, but there are no guarantees.

I don't know how much this plugin reacts with, or is used by, other plugins, so API style "breaking" might not apply. Otoh, changing what happens when the user types a space between elements would be a breaking change in the interface for the user.

Interestingly, the size of the change, or how much is changed or rewritten under the hood has no effect on the versions first tow numbers, only how it's seen by the "outside". Changing from vimscrpt to a C++ hook would still only be a part-three version bump.

**Comment by LunarWatcher** [comment]
API style breaking has applied. The move from `AutoPairs<FunctionNameWithoutBrackets>` to `autopairs#AutoPairs<FuncNameW/OBrackets>` was breaking. I knew I'd probably break something, which is why I initially went for v3. 

As long as -alpha makes sense as a current versioning system, I'll stick to it for now. 3.0.0 is fairly close, and I can rather get back to the specific versioning system later:tm:.
