### ISSUE TITLE
<M-e> (Alt-e) is not working as expected

### ISSUE THREAD

**Issue by ayush-mandowara-bst** [LunarWatcher/auto-pairs#20]
**OS**: Windows 10 2004
**What vim?: NVIM v0.4.4
**Reproduced in other variants of Vim?**: VIM - Vi IMproved 8.2

**Autopairs config**:
Although not applicable by I have the following config:
```
let g:AutoPairsDirectoryBlacklist = [$HOME . '\.config\vim']
```

### Actual Behaviour
- Press `<M-e>` on a matching pair such as `()`, `[]`, `''`
- No wrapping operation performed

### Expected Behavior
- word should be wrapped up by the matching pair
- `()test_word`
- cursor represented by |
- `(|)` press `<alt-e>` in insert mode
- (test_word)

**Comment by ayushxx7** [comment]
+1 (needed to raise the issue from this account)

**Comment by LunarWatcher** [comment]
#18 

I remapped all the meta mappings. Tried thinking about backwards compatibility options, but none really stood out. Can't exactly push uninstrusive warnings about a future breaking change. The change hasn't been labeled yet, though, so you can switch over to the latest tag while I sort out backwards compatibility options. I'll probably have to look into backwards-compatible ways of changing it. I didn't expect it to be breaking within two days :ablobsweats:

I'll rush the backwards compat to prevent further breaking. That being said

If you're interested in the new mappings, see the help doc (or the changelog; only `<C-f>` for fast wrap isn't mentioned in it -- need to fix that though)

if you don't like them, or muscle memory makes you prefer the old ones, you can revert all the changes with:

```vim
let g:AutoPairsShortcutToggle='<M-p>'
let g:AutoPairsShortcutFastWrap='<M-e>'
let g:AutoPairsShortcutJump='<M-n>'
let g:AutoPairsShortcutBackInsert='<M-b>'
```

Or, again, switch to 3.0.0-beta5 by specifying `{ 'tag': '*'}` (assuming vim-plug). There's only been one commit since the tag (the one changing mappings, to be specific), so you're not missing out on anything atm.

**Comment by ayushxx7** [comment]
cool thanks! I just switched to the tag.
- Comment Plugin
- `:PlugClean`
- Add Plugin with tag
```
Plug 'LunarWatcher/auto-pairs', { 'tag': '*' }      " opening brackets / quotes will add a matching closing pair
```
- `:PlugInstall`

Working as expected! 👍

**Comment by ayush-mandowara-bst** [comment]
closing. refer to the comment above by @ayushxx7 if you face a similar issue.

**Comment by LunarWatcher** [comment]
I'd actually like to leave this open until I sort out compatibility stuff, purely for tracking. Also makes it more clear that the issue is known and still relevant/active if anyone else runs into the same problem

**Comment by LunarWatcher** [comment]
Went with a variable - not the most optimal option, but it's the best I can do for the time being. It's set to 1 by default, which means `<M-e>` (among others) can be mapped. If you prefer these keybinds, I recommend setting `let g:AutoPairsCompatibleMaps = 1` to keep these keybinds -- I'll change the default to 0 some time in the future (though that'll at least be in a few months, so no rush). I'll keep the variable for backwards-compatibility with jiangmiao/auto-pairs regardless of the default, though.

**Comment by ayush-mandowara-bst** [comment]
Alright, cool! I've added `let g:AutoPairsCompatibleMaps = 1` to my settings.

**Comment by roachsinai** [comment]
@LunarWatcher for the lastest doc.txt version post below example about fastwrap:

```
        input: (|)'hello' (press (<M-e> at |)
        output: ('hello')

    Wrap string, only support c style string.
        input: |'h\\el\'lo' (press (<M-e> at |)
        output ('h\\ello\'')

        input: (|)[foo, bar()] (press (<M-e> at |)
        output: ([foo, bar()])
```

First, I think the first and third example `()` before piars and `(` before `<M-e>` is redundant.

And for the sencond example: `|'h\\el\'lo' (press (<M-e> at |)` I got: `('h\\el\')lo'`.

**Comment by LunarWatcher** [comment]
Yeah, that's me being dumb. Managed to miss the ( in front of the keybind.

**Comment by roachsinai** [comment]
> Yeah, that's me being dumb. Managed to miss the ( in front of the keybind.

lol, thanks again for your work!

**Comment by LunarWatcher** [comment]
The second example being broken is not me being dumb though. Gotta investigate that separately (suspecting bad regex somewhere)
