### ISSUE TITLE
[Feature] support Enter follow """ with characters

### ISSUE THREAD

**Issue by roachsinai** [LunarWatcher/auto-pairs#28]
For now what support is:

```
        input:
            """|""" (press <CR> at |)

        output:
            """
            |
            """

        input:
            """py or words to make a sentence|""" (press <CR> at |)

        output:
            """py or words to make a sentence
            |"""
```

Could the second be:

```
        input:
            """py or words to make a sentence|""" (press <CR> at |)

        output:
            """py or words to make a sentence
            |
            """
```

Thanks in advance!

**Comment by LunarWatcher** [comment]
This already exists, but is disabled by default. `let g:AutoPairsReturnOnEmptyOnly = 0`

The documentation needs a couple updates in this area though,aand it's probably about time I add a table of contents for variables

**Comment by roachsinai** [comment]
Yeah, work! Sorry I'm reading the doc, but not to that place.

**Comment by LunarWatcher** [comment]
It's perfectly fine - I'm not that used to writing Vim documentation,so readability might've tanked a bit. Relatively few complaints (direct or indirect) also mean I don't always question myself, because "I know where it is, so it's probably fine" (and that's a trash argument that I need to stop using).

There's also a few bits (largely the features overview) that hasn't gotten the updates it should've because I didn't think about it. Gonna clean up this and the deletion stuff when I'm properly awake :eyes:
