### ISSUE TITLE
Not working under debian 

### ISSUE THREAD

**Issue by werdahias** [LunarWatcher/auto-pairs#81]
**OS** (name + version; i.e. Linux Mint 20, Windows 10 2004, Macos Big Sur, etc.):
Debian 12 (bookworm)
**What vim? (+ version)** (i.e. vim, gvim, nvim, nvim-qt, mvim, ...):
```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled May 04 2023 10:24:44)
Included patches: 1-1378, 1499
```

**Reproduced in other variants of Vim?** (Optional):
n/a
**Autopairs config** (if applicable):
n/a
**Describe the bug**

**Steps to reproduce**
Grabbed the latest tarball and copied the plugin/autopairs.vim to ~/.vim/plugin .
Opening any file with vim results in: 

```
"plugin/autopairs.vim" 55L, 1967B
Error detected while processing BufEnter Autocommands for "*":
E117: Unknown function: autopairs#AutoPairsTryInit
Press ENTER or type command to continue
```

The only additional plugins installed are [vim-gruvbox ](https://github.com/morhetz/gruvbox)and [vim-rainbow](https://github.com/luochen1990/rainbow). I have to same issue when deactivating the rainbow plugin. The weird thing is that the "old" autopair plugin worked fine.

**Comment by LunarWatcher** [comment]
>  Grabbed the latest tarball and copied the plugin/autopairs.vim to ~/.vim/plugin .

Just that isn't sufficient. 

Unlike the original, this fork uses autoload for the bulk of the code. If you're manually installing it rather than using a plugin manager (which I massively recommend, for the record), the bare minimum to copy is `plugin/` and `autoload/`. The error you're getting is because `autopairs#AutoPairsTryInit` is in an autoload file, and not the plugin file

**Comment by werdahias** [comment]
ah sorry, copying the autoload folder makes it work.
